version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: ats-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      POSTGRES_DB: ${DB_NAME:-ats_database}
    ports:
      - "5432:5432" # Map cổng để bạn có thể connect từ máy thật (TablePlus/DBeaver)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-ats_database}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: